### ISSUE TITLE
0.3.0 release checklist

### ISSUE THREAD

**Issue by yallop** [dsheets/ocaml-unix-fcntl#10]
* [x] Add a more detailed [README][README] (#12)
* [x] Review the interface for consistency and completeness (#9, #11)
* [x] Bring the authors list up to date (#8)
* [x] Update the [changelog][changelog] (#8)
* [x] Check the build with and without optional dependencies
* [x] Update version numbers
* [x] Tag ([0.3.0](https://github.com/dsheets/ocaml-unix-fcntl/tree/0.3.0))
* [x] Publish on [opam-repository][opam-repository] (https://github.com/ocaml/opam-repository/pull/6246)

[README]: https://github.com/dsheets/ocaml-unix-fcntl/blob/master/README.md
[changelog]: https://github.com/dsheets/ocaml-unix-fcntl/blob/master/CHANGES
[opam-repository]: https://github.com/ocaml/opam-repository/

**Comment by yallop** [comment]
The [META][META] and [opam][opam] version numbers are already at `0.3.0`.  PR #8 (d7fd670a3) updates `CHANGES`.

[META]: https://github.com/dsheets/ocaml-unix-fcntl/blob/3eafa4f77cc40b3618098bdc02e0f50d8b104bb4/META#L1
[opam]: https://github.com/dsheets/ocaml-unix-fcntl/blob/3eafa4f77cc40b3618098bdc02e0f50d8b104bb4/opam#L3
